### PR TITLE
Implement optional JUnit XML output

### PR DESCRIPTION
**Pull request by AJIOB**
* Output JUnit XML file can be configured
* Test suite text name can be configured
* Fix some missing quotes & typos

This PR implements issue #16 in a basic variant.

### CODE REVIEW

**Review by williamdes — COMMENTED** [review]
Can you add a test case please ?

**Comment by AJIOB** [comment]
@williamdes, done.

**Review by williamdes — APPROVED** [review]
Thank you, this looks nice !

**Comment by AJIOB** [comment]
@williamdes, do we really need one more approval?

**Comment by AJIOB** [comment]
@williamdes, hello

Can we merge this PR?

**Comment by williamdes** [comment]
Hello, I am sorry but this is not my project
@kward can we discuss the project's state ?
Maybe transfer it into @code-lts org ?

**Comment by AJIOB** [comment]
Hi @williamdes 

There's still no activity. What about to merge this or create a fork to @code-lts & merge changes to the new fork?

**Comment by williamdes** [comment]
I merged your work, but we definitely need to find what is the way forward
Please @kward let us know

**Pull request merged**
